=== vladimilk/VMK/xml/actualizaciones.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT versiones (os+)>
<!ELEMENT os (version,nombre_codigo,numero_vercion,fecha_lanzamiento,nivel_api)>
<!ELEMENT fecha_lanzamiento (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT nombre_codigo (#PCDATA)>
<!ELEMENT numero_vercion (#PCDATA)>
<!ELEMENT nivel_api (#PCDATA)>

=== vladimilk/VMK/xml/actualizaciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='actualizaciones.xsl'?>
<!DOCTYPE versiones SYSTEM "actualizaciones.dtd">
<versiones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="actualizaciones.xsd">
  <os>
    <version>
      <nombre_codigo>Android 10</nombre_codigo>
      <numero_vercion>10.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>3</dia>
        <mes>Septiembre</mes>
        <anyo>2019</anyo>
      </fecha_lanzamiento>
      <nivel_api>29</nivel_api>
    </version>
    <version>
      <nombre_codigo>Pie</nombre_codigo>
      <numero_vercion>9.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>6</dia>
        <mes>Agosto</mes>
        <anyo>2018</anyo>
      </fecha_lanzamiento>
      <nivel_api>28</nivel_api>
    </version>
    <version>
      <nombre_codigo>Oreo</nombre_codigo>
      <numero_vercion>8.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>21</dia>
        <mes>Agosto</mes>
        <anyo>2017</anyo>
      </fecha_lanzamiento>
      <nivel_api>26</nivel_api>
    </version>
    <version>
      <nombre_codigo>Nougat</nombre_codigo>
      <numero_vercion>7.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>15</dia>
        <mes>Junio</mes>
        <anyo>2016</anyo>
      </fecha_lanzamiento>
      <nivel_api>24</nivel_api>
    </version>
    <version>
      <nombre_codigo>Marshmallow</nombre_codigo>
      <numero_vercion>6.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>5</dia>
        <mes>Octubre</mes>
        <anyo>2015</anyo>
      </fecha_lanzamiento>
      <nivel_api>23</nivel_api>
    </version>
    <version>
      <nombre_codigo>Lollipop</nombre_codigo>
      <numero_vercion>5.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>12</dia>
        <mes>Noviembre</mes>
        <anyo>2014</anyo>
      </fecha_lanzamiento>
      <nivel_api>21</nivel_api>
    </version>
  <version>
      <nombre_codigo>KitKat</nombre_codigo>
      <numero_vercion>4.4</numero_vercion>
      <fecha_lanzamiento>
        <dia>31</dia>
        <mes>Octubre</mes>
        <anyo>2013</anyo>
      </fecha_lanzamiento>
      <nivel_api>19</nivel_api>
    </version>
  <version>
      <nombre_codigo>Jelly Bean</nombre_codigo>
      <numero_vercion>4.1</numero_vercion>
      <fecha_lanzamiento>
        <dia>9</dia>
        <mes>Julio</mes>
        <anyo>2012</anyo>
      </fecha_lanzamiento>
      <nivel_api>16</nivel_api>
    </version>
  <version>
      <nombre_codigo>Ice Cream Sandwitch</nombre_codigo>
      <numero_vercion>4.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>18</dia>
        <mes>Octubre</mes>
        <anyo>2011</anyo>
      </fecha_lanzamiento>
      <nivel_api>14</nivel_api>
    </version>
  <version>
      <nombre_codigo>Honeycomb</nombre_codigo>
      <numero_vercion>3.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>22</dia>
        <mes>Febrero</mes>
        <anyo>2011</anyo>
      </fecha_lanzamiento>
      <nivel_api>11</nivel_api>
    </version>
  <version>
      <nombre_codigo>Gingerbread</nombre_codigo>
      <numero_vercion>2.3</numero_vercion>
      <fecha_lanzamiento>
        <dia>6</dia>
        <mes>Diciembre</mes>
        <anyo>2010</anyo>
      </fecha_lanzamiento>
      <nivel_api>9</nivel_api>
    </version>
  <version>
      <nombre_codigo>Froyo</nombre_codigo>
      <numero_vercion>2.2</numero_vercion>
      <fecha_lanzamiento>
        <dia>20</dia>
        <mes>Mayo</mes>
        <anyo>2010</anyo>
      </fecha_lanzamiento>
      <nivel_api>8</nivel_api>
    </version>
  <version >
      <nombre_codigo>Eclair</nombre_codigo>
      <numero_vercion>2.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>26</dia>
        <mes>Octubre</mes>
        <anyo>2009</anyo>
      </fecha_lanzamiento>
      <nivel_api>5</nivel_api>
    </version>
  <version>
      <nombre_codigo>Donut</nombre_codigo>
      <numero_vercion>1.6</numero_vercion>
      <fecha_lanzamiento>
        <dia>15</dia>
        <mes>Septiembre</mes>
        <anyo>2009</anyo>
      </fecha_lanzamiento>
      <nivel_api>4</nivel_api>
    </version>
  <version>
      <nombre_codigo>Cupcake</nombre_codigo>
      <numero_vercion>1.5</numero_vercion>
      <fecha_lanzamiento>
        <dia>15</dia>
        <mes>Abril</mes>
        <anyo>2009</anyo>
      </fecha_lanzamiento>
      <nivel_api>3</nivel_api>
    </version>
  <version>
      <nombre_codigo>Banana Bread</nombre_codigo>
      <numero_vercion>1.1</numero_vercion>
      <fecha_lanzamiento>
        <dia>9</dia>
        <mes>Febrero</mes>
        <anyo>2009</anyo>
      </fecha_lanzamiento>
      <nivel_api>2</nivel_api>
    </version>
  <version>
      <nombre_codigo>Apple Pie</nombre_codigo>
      <numero_vercion>1.0</numero_vercion>
      <fecha_lanzamiento>
        <dia>23</dia>
        <mes>Septiembre</mes>
        <anyo>2008</anyo>
      </fecha_lanzamiento>
      <nivel_api>29</nivel_api>
    </version>
  </os>
</versiones>
